Topic
GuillaumeOz/ft_irc pull request #67
Opened 2022-03-03 14:27 UTC by GuillaumeOz

✨ - Add TOPIC Cmd.
♻️ - Refactor of error handling responses system.

2022-03-03 17:28 UTC, nabitbol requested changes
Fix segfault error when the user call Topic before creating a channel and after creating a channel

2022-03-04 15:58 UTC, thibautgontier approved these changes

2022-03-04 15:58 UTC, thibautgontier commented
looks good!

2022-03-04 15:59 UTC, thibautgontier approved these changes

2022-03-04 16:00 UTC, thibautgontier approved these changes

2022-03-04 19:09 UTC, nabitbol approved these changes

2022-03-04 19:09 UTC, merged